dist:
  - trusty

language:
  - cpp

sudo:
  - false

os:
  - linux

addons:
  apt:
    packages:
      - mlton
      - smlnj
      - libsmlnj-smlnj
      
before_install:
  - ( cd ../ ; hg clone https://bitbucket.org/cannam/sml-buildscripts )

script:
  - make test
  - ../sml-buildscripts/smlrun test.mlb | tee test.log
  - ! grep -q "^FAIL" test.log
